# Generated by Django 2.2.4 on 2019-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('link', models.CharField(max_length=250)),
                ('img_src', models.CharField(max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(to='collection.Ingredient')),
            ],
        ),
    ]
