# Generated by Django 2.2.4 on 2019-09-29 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_objects',
            field=models.ManyToManyField(blank=True, to='collection.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_strings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
