# Generated by Django 2.2.4 on 2019-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[('EACH', 'Each'), ('CUP', 'Cup'), ('TABLESPOON', 'Tablespoon'), ('TEASPOON', 'teaspoon'), ('OUNCE', 'Ounce'), ('POUND', 'Pound')]),
        ),
    ]
