# Generated by Django 2.2.4 on 2019-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190929_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
