# Generated by Django 2.2.4 on 2019-09-29 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190929_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_strings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
